# Introduction

In [39]:
import numpy as np

print(np.__version__)

2.4.4


In [40]:
a = np.array([1, 3, 6, 9], dtype='int16')
print(a)

[1 3 6 9]


In [41]:
b = np.array([[3.0,9.0,5.0], [1.,79.0,4.9]])
print(b)

[[ 3.   9.   5. ]
 [ 1.  79.   4.9]]


In [42]:
print('1D Array')
x = np.array([1, 2, 3, 4, 5])
print(x)


#----------------------------


print('2D Array')
y = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10]])
print(y)


#----------------------------

print('3D Array')
z = np.array([[[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15]]])
print(z)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [43]:
type(x)

numpy.ndarray

In [44]:
#Get Dimension
a.ndim

1

In [45]:
b.ndim

2

In [46]:
#Get Shape
b.shape

(2, 3)

In [47]:
a.shape

(4,)

In [48]:
#Get Type
a.dtype

dtype('int16')

In [49]:
#Get Size
a.size

4

In [50]:
#Get Total Size
a.nbytes

8

In [51]:
d = np.array([[1, 2, 3, 4.2, 5], 
              [6, 7, 8.9, 9, 10], 
              [11, 12, 13, 14, 15]])

print(d.dtype)

float64


In [52]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

# initialize different types of arrays

## random integers

In [ ]:
#Random float number (uniformally distributed around 0 and 1)
np.random.rand(4, 3, 2)

In [ ]:
#Random float number (uniformally distributed around -1 and 1)
np.random.randn(4, 3, 2)

In [ ]:
np.random.random_sample(a.shape)

In [ ]:
#Random integer values
np.random.randint(-4, 9, size=(3,3))

In [ ]:
#Saving the random value generated to the memory for further use
np.random.seed(1)
np.random.randint(-4, 9, size=(3,3))

In [ ]:
#generating a matrix with random integers between 0 & 4
rng = np.random.default_rng(0)
rng.integers(5, size=(2, 4))

## array with ones

In [53]:
#np.empty((rows, cols), dtype)
np.empty((4,4), dtype = float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
#np.ones((rows, cols), dtype)
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [55]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
#All 1s matrix
np.ones((4, 5, 3), dtype = 'int16')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

## array with zeros
np.zeros((rows, cols), dtype)

In [58]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [59]:
y = np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
z = np.zeros((4,8), dtype = int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
z = np.zeros((4,8), dtype = str)
z

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')

In [62]:
z = np.zeros((4,8), dtype = bool)
z

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [63]:
np.zeros((3,6,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [64]:
#Any other number
np.full((3,5), 77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [65]:
#Any other number (full_like)
np.full_like(a, 4)

array([4, 4, 4, 4], dtype=int16)

## array using arange/repeat/unique

np.arange(start, end, step)

In [ ]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.arange(1,20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
a = np.arange(2,20, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [ ]:
#generating an array with as many elemnts we want
np.linspace(1,50,30)

In [ ]:
#generating an array with equqlly space log scale elements
np.logspace(1,50,10)

In [ ]:
#the identity matrix
np.identity(5)

In [ ]:
#repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

In [ ]:
#repeating an array with tile()
np.tile(arr, 4)

In [ ]:
#get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
uni = np.unique(a)
print(uni)

In [ ]:
#Get the indices of unique values
uni, ind = np.unique(a ,return_index=True)
print(ind)

In [ ]:
#Get the count of unique values
uni, count = np.unique(a, return_counts=True)
print(count)

# Array Operations on specific elements, rows, columns, etc.

## accessing

In [ ]:
### 2-D Array
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [67]:
#Get a specific element [r, c]
a[1,5] 
#or a[1,-2]

np.int64(13)

In [68]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
#Get a specific column
a[:, 4]

array([ 5, 12])

In [70]:
#Doing more specific elements [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [71]:
#Re-assigning values in the array
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [72]:
#Get element 5 and up
print((a>5) | (a==5))

[[False False False False  True  True  True]
 [ True  True  True  True  True  True  True]]


In [73]:
a = np.arange(1,51)
a = a.reshape(10,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [74]:
a[0]

array([1, 2, 3, 4, 5])

In [75]:
a[2]

array([11, 12, 13, 14, 15])

In [76]:
print(a[0,0])
print(a[3,4])
print(a[2:5])

1
20
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [77]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [78]:
a[:, 2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [79]:
a[2:5, 4]

array([15, 20, 25])

In [80]:
a[:, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [81]:
a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [ ]:
### 3-D Array
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [83]:
#Get specific element  (work outside in)
b[0,1,:]

array([3, 4])

In [84]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [85]:
b[0,:,1]

array([2, 4])

In [86]:
c = np.array([[1,4,1], [2,7,2], [3,9,3]])
c

array([[1, 4, 1],
       [2, 7, 2],
       [3, 9, 3]])

In [87]:
#Reversing the order of row by subsetting 
c[:: -1, ]

array([[3, 9, 3],
       [2, 7, 2],
       [1, 4, 1]])

In [88]:
#reversing the order of rows & columns by subsetting
c[:: - 1, :: -1]

array([[3, 9, 3],
       [2, 7, 2],
       [1, 4, 1]])

In [89]:
#Replacing elements in the array
b[:,1,:] = [[78,34], [22,56]]
print(b)

[[[ 1  2]
  [78 34]]

 [[ 5  6]
  [22 56]]]


## How to add a new axis to an array

In [ ]:
#Replacing elements in the array
b[:,1,:] = [[78,34], [22,56]]
print(b)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

In [ ]:
a2 = a[np.newaxis, :] #row_vector
a2.shape

In [ ]:
a3 = a[:, np.newaxis] #col_vector
a3.shape

## reshaping

In [93]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [94]:
b = np.arange(1,100,2)
b


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [95]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [ ]:
#Use transpose() to reverse the axes of an array
#before was 2x4 matrix
#before.transpose() is 4x2 matrix
b.transpose()

In [ ]:
#flipping 1-D arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
rev= np.flip(arr)
print('Reversed array: ', rev)

In [ ]:
#flipping 2-D arrays
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
rev_2d = np.flip(arr_2d)
print(rev_2d)

In [ ]:
#reversing rows
rev_row = np.flip(arr_2d, axis = 0)
print(rev_row)

In [ ]:
#reversing columns
rev_col = np.flip(arr_2d, axis=1)
print(rev_col)

In [ ]:
#flipping only second row
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

In [ ]:
#fliping second column
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

## flatten & ravel


In [96]:
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [97]:
#flatten() 
#Return copy of original array #
# If you modify any value of this array value of original array is not affected. #
# Flatten() is comparatively slower than ravel() as it occupies memory. #
# Flatten is a method of an ndarray object.

In [98]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
###ravel(): 
#Return only reference/view of original array 
#If you modify the array you would notice that the value of original array also changes. 
#Ravel is faster than flatten() as it does not occupy any memory. 
#Ravel is a library-level function.


# math Operations on arrays

### add ,sub,multiple

In [100]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20, 38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [101]:
a+b
#or np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [117]:
a + 2

array([3, 4, 5, 6, 7])

In [102]:
a-b
#or np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [ ]:
a - 2

In [103]:
a*b
#or np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [ ]:
a * 2

In [104]:
a/b
#or np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [105]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [106]:
b = b.reshape((3,6))

In [107]:
print(a.shape)
print(b.shape)

(6, 3)
(3, 6)


In [ ]:
a@b
#a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [ ]:
b.max()

In [ ]:
b.min()

In [109]:
np.sum(b)

np.int64(513)

In [114]:
np.sum(b, axis = 1)#return the sum of elements of rows of array b


array([135, 171, 207])

In [112]:
np.sum(b, axis = 0)#return the sum of elements of columns of array b

array([78, 81, 84, 87, 90, 93])

In [ ]:
np.mean(b)

In [ ]:
np.sqrt(b)

In [ ]:
np.std(b)

In [ ]:
np.std(b)

### sin,cos,tan,log,exp

In [ ]:
#Take sin of an array
np.sin(a)

#cos and tan values of a 
#np.cos(a)
#np.tan(a)

### floor & ceil & round

In [ ]:
#floor() ---it return groud value of an element
#ceil() ---it return high value of an element

In [ ]:

x=np.array([1.2,1.3,5.67,8.97])

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

In [ ]:
#round()--- it will round to nearest value
np.round(x)

# Stacking 

In [ ]:
#it is merging of two arrays
#1- vertical stacking----number of columns should be same
#2- horizontal stacking---number of rows must be same

In [115]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [116]:
np.stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
### horizontal & vertical stacking
a=np.arange(0,12).reshape((3,4))
b=np.arange(20,38).reshape((3,6))

In [ ]:
print(a)
print(b)

In [ ]:
np.hstack((a,b))

In [ ]:
a.reshape((2,6))

In [ ]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

np.vstack([v1,v2])

In [ ]:
np.vstack([v1,v2, v2, v1])

In [ ]:
#Horizantally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

In [ ]:
np.hstack([h1,h2,h2,h1,h2,h1])

# splitting array

In [ ]:
#Splitting long arrays into small arrays
x = np.arange(1,25).reshape(2,12)
np.hsplit(x,3)

In [ ]:
np.hsplit(x,4)

In [ ]:
np.hsplit(x, (3,4))

# Sorting arrays

In [ ]:
kk = np.random.randint(1,10,size = [10,5])
kk

In [ ]:
#sorting along rows of the array
np.sort(kk)

In [ ]:
#sorting a single a col
sorted_col = kk[:, 0].argsort()
kk[sorted_col]

# wroking with dates

In [ ]:
d = np.datetime64('2021-08-03 23:10:00')
d

In [ ]:
#adding seconds to the date-time
d + 100000

In [ ]:
#adding one day to the date-time
oneday = np.timedelta64(1, "D")
oneday
d + oneday

In [ ]:
#adding one minute to the date-time
onemin = np.timedelta64(1, 'm')
onemin
d + onemin

In [ ]:
#creating a sequence of date-time array
dates = np.arange(np.datetime64('2019-09-03'), np.datetime64('2019-10-03'), 3)
dates

In [ ]:
dates = np.arange(np.datetime64('2019-09-03'), np.datetime64('2019-10-03'))
dates

# data operations

### loading data from file

In [121]:
data = np.genfromtxt('data.txt', delimiter = ',')
data

FileNotFoundError: data.txt not found.

In [ ]:
### changing the data type of an file
data = data.astype('int32')
data

### Loading from url

In [ ]:
dta= np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv', delimiter =',', skip_header = 1)
dta

FileNotFoundError: https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv not found.

### Filling NaN values with other values

In [ ]:
dta= np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv', delimiter =',', skip_header = 1, 
                  filling_values= 9999, dtype = 'float')
dta

### Supressing Scientific Notation in the Dataset

In [ ]:
np.set_printoptions(suppress=True)
dta

### Saving Files into Local

In [ ]:
np.savetxt('auto.csv', dta, delimiter = ',')

### Loading Files through NumPy

In [ ]:
k = np.load('auto.npy')
k