# ******* Part 1 *******

In [1]:
import numpy as np

In [2]:
lst =  [1, 2, 3, 4, 5]
print(lst)

[1, 2, 3, 4, 5]


**Advantage of Numpy Array over Lists**

In [3]:
print('1D Array')
a = np.array([1, 2, 3, 4, 5])
print(a)


#----------------------------


print('2D Array')
b = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10]])
print(b)


#----------------------------

print('3D Array')
c = np.array([[[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15]]])
print(c)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [4]:
type(a)

numpy.ndarray

**size = Tells about no. of elements in that array**

In [5]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


**shape = (rows, cols)**

In [6]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


**dtype = Type of Data Present in the array**

In [7]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [8]:
d = np.array([[1, 2, 3, 4.2, 5], 
              [6, 7, 8.9, 9, 10], 
              [11, 12, 13, 14, 15]])

print(d.dtype)

float64


arr.transpose()

In [9]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

#ndim----returns dimnetions of an array
type(arr)---returns type of array


In [10]:
type(d)

numpy.ndarray

# *************************** Part 2 ***************************

**np.empty((rows, cols), dtype)**

In [11]:
np.empty((4,4), dtype = float)

array([[4.67296267e-310, 0.00000000e+000, 2.41907520e-312,
        2.14321575e-312],
       [2.46151512e-312, 2.31297541e-312, 2.35541533e-312,
        2.05833592e-312],
       [2.22809558e-312, 2.56761491e-312, 2.48273508e-312,
        2.05833592e-312],
       [2.05833592e-312, 2.29175545e-312, 2.07955588e-312,
        2.14321575e-312]])

**np.ones((rows, cols), dtype)**

In [12]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [13]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**np.zeros((rows, cols), dtype)**

In [15]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [16]:
y = np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
z = np.zeros((4,8), dtype = int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
z = np.zeros((4,8), dtype = str)
z

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')

In [19]:
z = np.zeros((4,8), dtype = bool)
z

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

# *************************** Part 3 ***************************

**np.arange(start, end, step)**

In [20]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
a = np.arange(1,20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [22]:
a = np.arange(2,20, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


**arr.reshape((rows, cols))**

In [23]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [25]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [26]:
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [27]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

a.ravel():
(i) Return only reference/view of original array
(ii) If you modify the array you would notice that the value of original array also changes.
(iii) Ravel is faster than flatten() as it does not occupy any memory.
(iv) Ravel is a library-level function.

a.flatten() :
(i) Return copy of original array
(ii) If you modify any value of this array value of original array is not affected.
(iii) Flatten() is comparatively slower than ravel() as it occupies memory.
(iv) Flatten is a method of an ndarray object.

# *************************** Part 4 ***************************

In [28]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [29]:
a[0]

array([1, 2, 3, 4, 5])

In [30]:
a[2]

array([11, 12, 13, 14, 15])

In [31]:
a[0,0]

1

In [32]:
a[3,4]

20

In [33]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [35]:
a[:, 2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [36]:
a[2:5, 4]

array([15, 20, 25])

In [37]:
a[:, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [38]:
a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [39]:
a[:, 2:5].dtype

dtype('int64')

# *************************** Part 5 ***************************

In [40]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20, 38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [41]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [42]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [43]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [44]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [45]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [46]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [47]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [48]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [49]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [ ]:
print(a.shape)
print(b.shape)

In [ ]:
b = b.reshape((3,6))

In [ ]:
print(a.shape)
print(b.shape)

In [ ]:
a@b

In [ ]:
a.dot(b)

In [ ]:
b.max()

In [ ]:
b.min()

In [ ]:
b.argmax()

In [ ]:
np.sum(b)

In [ ]:
np.sum(b, axis = 1)#return the sum of elements of rows of array b

In [ ]:
b.shape


In [ ]:
np.sum(b, axis = 0)#it returns the sum of columns of an array

In [ ]:
np.mean(b)

In [ ]:
np.sqrt(b)

In [ ]:
np.std(b)

In [ ]:
np.log(b)

* floor() ---it return groud value of an element
* ceil() ---it return high value of an element

In [ ]:
x=np.array([1.2,1.3,5.67,8.97])

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

* round()--- it will round to nearest value

In [ ]:
np.round(x)

************stacking***********----it is merging of two arrays
1. vertical stacking----number of columns should be same 
1. horizontal stacking---number of rows must be same

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [ ]:
np.stack((a,b))

1. hstack()----horizontal stacking (row-wise)
1. vstack()----vertical stacking(column -wise)

In [ ]:
a=np.arange(0,12).reshape((3,4))
b=np.arange(20,38).reshape((3,6))

In [ ]:
print(a)
print(b)

In [ ]:
np.hstack((a,b))

In [ ]:
a.reshape((2,6))

In [ ]:
# np.vstack((a,b))

**split**

In [ ]:
#vertical split----splits the array into multiple array vertically(row wise)
#horizontal split----splits the array into multiple array horizontally(column wise)
#sytax==np.split(array_name,no.of.arrays)
a=np.arange(100).reshape((10,10))
a

In [ ]:
np.vsplit(a,2)

In [ ]:
np.hsplit(a,2)

In [ ]:
#linspace---it create randomly genrated vlaues between st and end(note:it include end aslo)
np.linspace(0,30)#it include 30 also

# *************************** Part 6 ***************************

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [ ]:
np.pi

In [ ]:
np.sin(np.pi/2) # 90 degrees

In [ ]:
np.sin(np.pi/6) 

In [ ]:
np.cos(np.pi/2)

In [ ]:
np.tan(np.pi/2)

In [ ]:
np.tan(0)

**Using Matplotlib with Numpy**

In [ ]:
x = np.arange(1,11)
y = np.arange(10, 110, 10)

plt.figure(figsize = (6,6))
plt.plot(x,y, 'r--')
plt.show()

**Plotting Trigonometric Curves**

In [ ]:
x_sin = np.arange(0,2*np.pi, 0.1)
y_sin = np.sin(x_sin)

print(y_sin)

In [ ]:
plt.figure(figsize = (6,6))
plt.plot(x_sin, y_sin)
plt.title('Sin Curve')
plt.show()

In [ ]:
x_cos = np.arange(0, 2*np.pi, 0.1)
y_cos = np.cos(x_cos)

plt.figure(figsize = (6,6))
plt.plot(x_cos, y_cos)
plt.title('Cos Curve')
plt.show()

In [ ]:
x_tan = np.arange(0, 2*np.pi, 0.1)
y_tan = np.tan(x_tan)

plt.figure(figsize = (6,6))
plt.plot(x_tan, y_tan)
plt.title('Tan Curve')
plt.show()

In [ ]:
x_cot = np.arange(0, 2*np.pi, 0.1)
y_cot = 1/np.tan(x_cot)

plt.figure(figsize = (6,6))
plt.plot(x_cot, y_cot)
plt.title('Cot Curve')
plt.show()

**Subplot**

In [ ]:
plt.figure(figsize = (6,6))
plt.subplot(2,2,1)
plt.plot(x_sin, y_sin, 'r-')
plt.title('Sin Curve')

plt.subplot(2,2,2)
plt.plot(x_cos, y_cos, 'b-')
plt.title('Cos Curve')

plt.subplot(2,2,3)
plt.plot(x_tan, y_tan, 'g-')
plt.title('Tan Curve')

plt.subplot(2,2,4)
plt.plot(x_cot, y_cot, 'w-')
plt.title('Cot Curve')

plt.show()


# *************************** Part 7 ***************************

In [ ]:
np.random.random(1)

In [ ]:
#random
np.random.random(2)#it will given an random 2 numbers

In [ ]:
 np.random.random((2,2)) #it will given an array of 2 by 2 having random values

In [ ]:
#randint
np.random.randint(1,10) #it will return random number between given range(1,10)

In [ ]:
np.random.randint(1,10, (2,2))

In [ ]:
np.random.randint(1,10, (3,4,5))

In [ ]:
#rand---it will return array of floating values in 2 by 2 dimension.
np.random.rand(2,2)

In [ ]:
#randn----it will return array of negative values also
np.random.randn(2,2)

In [ ]:
a = np.arange(1,10)
print(a)

In [ ]:
#choice---it will return random number from an given array
np.random.choice(a)

# *************************** Part 8 ***************************

In [ ]:
s1 = 'Akshit is my name'
s2 = 'I am an Indian'

In [ ]:
np.char.add(s1, s2)

In [ ]:
np.char.upper(s1)

In [ ]:
np.char.lower(s1)

In [ ]:
np.char.split(s1)

In [ ]:
s3 = 'Akshit is my\nname'
np.char.splitlines(s3)

In [ ]:
np.char.replace(s1, 'name', 'sirname')

In [ ]:
print('**********good bye***********')

In [ ]:
print(np.char.center('good bye', 80, '*'))